@startuml CVM

[*] --> S_INITIALISE_SYSTEM : E_START

S_INITIALISE_SYSTEM --> S_INITIALISE_SENSORS : E_INIT_DONE
S_INITIALISE_SYSTEM --> S_ERROR : E_INIT_ERROR

S_INITIALISE_SENSORS --> S_IDLE : E_SENSOR_INIT_DONE
S_INITIALISE_SENSORS --> S_ERROR : E_INIT_ERROR

S_IDLE --> S_UPDATE_ENVIRONMENT : E_TICK
S_UPDATE_ENVIRONMENT --> S_READ_SENSORS : E_ENV_UPDATED
S_READ_SENSORS --> S_PROCESS_DATA : E_SENSOR_READ
S_PROCESS_DATA --> S_STORE_DATA : E_DATA_PROCESSED
S_STORE_DATA --> S_IDLE : E_DATA_STORED

S_IDLE --> S_PAUSE : E_PAUSE
S_PAUSE --> S_IDLE : E_RESUME

S_IDLE --> S_STOP : E_STOP
S_UPDATE_ENVIRONMENT --> S_ERROR : E_ERROR
S_READ_SENSORS --> S_ERROR : E_ERROR
S_PROCESS_DATA --> S_ERROR : E_ERROR
S_STORE_DATA --> S_ERROR : E_ERROR

S_ERROR --> S_RECOVER : E_ERROR
S_RECOVER --> S_IDLE : E_RECOVERED

@enduml
