@startuml CVM

[*] --> S_START : E_START

S_START --> S_INITIALISE_SYSTEM : E_START
S_INITIALISE_SYSTEM --> S_INIT_DASHBOARD : E_INIT_DONE

S_INIT_DASHBOARD --> S_READ_SENSORS : E_DASHBOARD_INIT
S_READ_SENSORS --> S_UPDATE_ENVIRONMENT : E_SENSOR_READ
S_UPDATE_ENVIRONMENT --> S_DASHBOARD : E_ENV_UPDATED

S_DASHBOARD --> S_SWITCH_UNITS : E_SWITCH_UNITS
S_SWITCH_UNITS --> S_UPDATE_ENVIRONMENT : E_SWITCH_UNITS

S_DASHBOARD --> S_HISTORY : E_SHOW_HISTORY
S_HISTORY --> S_INIT_DASHBOARD : E_DASHBOARD_INIT

S_DASHBOARD --> S_READ_SENSORS : E_SENSOR_READ
S_DASHBOARD --> S_STOP : E_DASHBOARD_EXIT

@enduml
